### ISSUE TITLE
file header in test dataset file treated as data item

### ISSUE THREAD

**Issue by robertvi** [UCLOrengoGroup/cath-alphaflow#36]
https://github.com/UCLOrengoGroup/cath-alphaflow/blob/main/tests/fixtures/dataset100/dataset100.uniprot_domain_ids.csv

The above file starts with a column header as the first line, but is processed as if all lines are uniprot domain ids here:

https://github.com/UCLOrengoGroup/cath-alphaflow/blob/main/workflows/cath-shared.nf#L86

consequently a corresponding file is attempted to be downloaded called AF-uniprot_domain_id-F*.cif etc

It probably ends up in the list of missing items that failed to download?

This could be fixed by forbidding headers in the input file, or by explicitly filtering out the expected header string, or always excluding the first line of the file (ie requiring exactly one line of header in all input files).

**Comment by robertvi** [comment]
or could process the csv using nextflow splitcsv, which can look for and remove a specific header
https://www.nextflow.io/docs/latest/operator.html#splitcsv

**Comment by sillitoe** [comment]
Using `splitCsv(header: true)` feature is a nice idea. I guess one disadvantage is that this would break if someone provided a CSV file without header. I'm thinking that could easily happen by accident - the result being that the initial row would be silently ignored. I guess the advantage of explicitly filtering out the header is that it plays nicely with a csv without headers.

```
cat with_or_without_headers.csv | grep -v header_col_name | ...
```

The disadvantage is that it's not great to explicitly hard code `header_col_name` into this code. I guess we could at least move this to parameters.

**Comment by robertvi** [comment]
splitCsv(header=["uniprot_domain_id"]) or splitCsv(header=[${param.udi_header}]) might cope with headered and headerless files, but nextflow docs are not clear if this requires the header or makes it optional, will try to test it at some point
