### ISSUE TITLE
Add check for gsutil and put in sub-module

### ISSUE THREAD

**Issue by Rachel-Alcraft** [UCLOrengoGroup/cath-alphaflow#37]
Currently the call to gsutil allows failures which includes non-authetication as well as missing files.
Change this to multiple calls to check authentication, and make it a sub-module.

This is necessary to understand if any nodes fail whn distributed on the clusters. There is a seperate consideration about how the files chunk if there are any missing.

**Comment by Rachel-Alcraft** [comment]
Need a servce account for the nodes:
https://cloud.google.com/sdk/docs/authorizing: 
gcloud auth login --cred-file=CONFIGURATION_OR_KEY_FILE

**Comment by robertvi** [comment]
Ian's original suggestion was to use "gcloud auth application-default login" which seems to be for:
"This command is useful when you are developing code that would normally use a service account but need to run the code in a local development environment where it's easier to provide user credentials"
Does that help?

**Comment by Rachel-Alcraft** [comment]
Have you managed to get it working on cluster nodes? It's fine to login on Myriad and get it working through nextflow locally, but I am struggling to provision the nodes - it doesn't re-use the local provision on the nodes as far as I can tell.

**Comment by robertvi** [comment]
It works on cs nodes using an interactive login, but that's cheating because I am still manually pasting in the auth string on the node that then runs the tasks. Testing proper qsub based non interactive job execution now...

**Comment by robertvi** [comment]
maybe put a https://www.nextflow.io/docs/latest/process.html#beforescript directive to a script that sets up auth for every process that needs it?

**Comment by Rachel-Alcraft** [comment]
Yes, I don't know what to put in the script! Have you got the nodes working?

**Comment by robertvi** [comment]
So far only got jobs submitted, nothing has reached front of the queue yet! Probably will all get cancelled when I move to the meeting and wifi cuts out briefly :P

**Comment by Rachel-Alcraft** [comment]
Deprecated effectively by the platform-specific config
