### ISSUE TITLE
Work out a nextflow config for automated qsub jobs on CS cluster

### ISSUE THREAD

**Issue by robertvi** [UCLOrengoGroup/cath-alphaflow#38]
Previously I've only been running nextflow on one compute node in an interactive session. Now I'm testing running the nextflow launcher on the login node but submitting jobs to compute nodes using qsub via nextflow's executor settings.

**Comment by robertvi** [comment]
I have added labels to the processes which refer to config blocks in the nextflow.config file. The current labels are "default_sge" meaning the job runs via qsub on a compute node, and "default_local" meaning it runs on the local machine which is usually the login node (so this is obviously only suitable to small, resource light, processes).

**Comment by robertvi** [comment]
```
[rvickers@pchuckle cath-alphaflow]$ source ./platforms/ucl_cs_cluster/source
WARNING: Re-using locally stored credentials for [robert.vickerstaff.aws@gmail.com]. To fetch new credentials, re-run the command with the `--force` flag.

You are now logged in as [robert.vickerstaff.aws@gmail.com].
Your current project is [None].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID
(cath_venv) [rvickers@pchuckle cath-alphaflow]$ nextflow run -resume ./workflows/cath-test-workflow.nf
N E X T F L O W  ~  version 22.10.6
WARN: It appears you have never run this project before -- Option `-resume` is ignored
Launching `./workflows/cath-test-workflow.nf` [goofy_lavoisier] DSL2 - revision: 382e6e9c45
executor >  sge (44)
[cd/e04000] process > uniprot_domain_to_uniprot (1)         [100%] 1 of 1 ✔
[55/c4dc3f] process > create_af_manifest_file (10)          [100%] 11 of 11 ✔
[14/f38ad5] process > retrieve_af_chain_cif_files (11)      [100%] 11 of 11 ✔
[c9/6fb54f] process > chop_cif (10)                         [100%] 10 of 10 ✔
[de/58ad80] process > cif_paths_to_uniprot_accessions (8)   [100%] 10 of 10 ✔
[0b/c28c85] process > create_missing_uniprot_domain_ids (1) [100%] 1 of 1 ✔
Completed at: 01-Feb-2023 11:55:08
Duration    : 8m 44s
CPU hours   : 0.1
Succeeded   : 44


(cath_venv) [rvickers@pchuckle cath-alphaflow]$ 
```

**Comment by robertvi** [comment]
nextflow.config is a symlink to the platform specific file, I had to insert a tmem resource request into the gridengine options using clusterOptions, and also the beforeScript has to run the same "source" script that I manually source to setup nextflow on the login node, this seems to be happy just reusing any existing gcloud authentication tokens found under ~/.gcloud, so should be available across all compute nodes - I don't know if they time out, but it should automatically prompt you for another authentication token when you manually source the config on the login node prior to running nextflow

**Comment by robertvi** [comment]
We probably want a common nextflow config file and then somehow selectively override only the bits that change between platforms. But the differences could get quite extensive in the worst case: eg on Myriad I think all compute nodes are also submit nodes, so you could run "local" jobs on an interactive compute node login which were quite resource hungry, and have the same nextflow instance launch jobs on other computer nodes to get parallelism. Whereas on CS the compute nodes are note submit nodes, so you are reduced to running only small "local" jobs on the login node and a lot more processes via qsub. Advantages of running more steps locally on a compute node are that fast local scratch is therefore shared between those steps, and there is no queue delay between the steps (but obviously you are limited to the resources of a single compute node still)

**Comment by Rachel-Alcraft** [comment]
nf-core have many config files per platform, just saying in case either we want a similar approach or perhaps they have come up with a good reason for it! It is very convenient as it is how I got a working config for the cath test.
https://github.com/nf-core/configs/tree/master/conf
