### ISSUE TITLE
Is there any document for this repo?

### ISSUE THREAD

**Issue by KatarinaYuan** [UCLOrengoGroup/cath-alphaflow#61]
Hi, wondering if there is any document for the repo? I'm quite new to CATH and feel quite lost about how to use the CLI.

Thank you!

**Comment by sillitoe** [comment]
Hi. This repo is recoding a data pipeline that required manual steps into one that takes advantage of a more modern workflow framework (NextFlow). This work will be covered in detail in a scientific article at some point in the future, but currently the best document for this repo is the README.md.

If you want to find out more about CATH, then it's best to look at the [website](https://www.cathdb.info) or [recent articles](https://pubmed.ncbi.nlm.nih.gov/?term=cath+orengo).
